name: Tests

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  watch:
    types: [started]

jobs:
  tests:
    name: run tests
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - uses: actions/checkout@v2
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: run test
  build-and-publish:
    needs: tests
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
